### ISSUE TITLE
Upgrading Frontend

### ISSUE THREAD

**Issue by shan18** [shan18/Stock-Bridge#11]
Upgrade the frontend design of the entire project. At least the following points should be taken care of:
- Add a footer
- Add jQuery to various buttons
- Improve the homepage design
- Add better messages to the django-messages function
- Other miscellaneous changes

**Comment by vipulyadav150** [comment]
Solved update of messages in pull request #22

**Comment by shan18** [comment]
Updated transaction view in commit ad5eb70a994ba8bdae32d84cd4f0bee5c598dfad.

**Comment by shan18** [comment]
- Adding jQuery: a1f2102edc91566d8630ad68d2b9ea30e3bcfa6f
- Transaction Page: b2cbeab38125fa1749d97d489a20c3e4301683ca

**Comment by shan18** [comment]
Add jQuery to bank view in 19dd35a1a089d39b481c7f656e8db8da72973d57.

**Comment by shan18** [comment]
Add company marqee in 135d7a8e9beca128e37ccfe167b12347a134b408.

**Comment by shan18** [comment]
Improve home page in 39536711cc866aa25872c769c8a214c6faa330ce.

**Comment by shan18** [comment]
Finished in 97d4d13f9b103dd0e53d855843ce61adb8022d66.
